<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurriculumSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("curriculums")->insert([
            ['discipline_id' => 1,  'speciality_id' => 1],
            ['discipline_id' => 2,  'speciality_id' => 1],
            ['discipline_id' => 3,  'speciality_id' => 1],
            ['discipline_id' => 4,  'speciality_id' => 1],
            ['discipline_id' => 5,  'speciality_id' => 1],
            ['discipline_id' => 7,  'speciality_id' => 1],
            ['discipline_id' => 8,  'speciality_id' => 1],
            ['discipline_id' => 9,  'speciality_id' => 1],
            ['discipline_id' => 10, 'speciality_id' => 1],
            ['discipline_id' => 11, 'speciality_id' => 1],
            ['discipline_id' => 12, 'speciality_id' => 1],
            ['discipline_id' => 13, 'speciality_id' => 1],
            ['discipline_id' => 14, 'speciality_id' => 1],
            ['discipline_id' => 15, 'speciality_id' => 1],
            ['discipline_id' => 16, 'speciality_id' => 1],
            ['discipline_id' => 17, 'speciality_id' => 1],
            ['discipline_id' => 18, 'speciality_id' => 1],

            ['discipline_id' => 1,  'speciality_id' => 2],
            ['discipline_id' => 2,  'speciality_id' => 2],
            ['discipline_id' => 3,  'speciality_id' => 2],
            ['discipline_id' => 4,  'speciality_id' => 2],
            ['discipline_id' => 5,  'speciality_id' => 2],
            ['discipline_id' => 7,  'speciality_id' => 2],
            ['discipline_id' => 8,  'speciality_id' => 2],
            ['discipline_id' => 9,  'speciality_id' => 2],
            ['discipline_id' => 10, 'speciality_id' => 2],
            ['discipline_id' => 11, 'speciality_id' => 2],
            ['discipline_id' => 12, 'speciality_id' => 2],
            ['discipline_id' => 13, 'speciality_id' => 2],
            ['discipline_id' => 14, 'speciality_id' => 2],
            ['discipline_id' => 15, 'speciality_id' => 2],
            ['discipline_id' => 16, 'speciality_id' => 2],
            ['discipline_id' => 17, 'speciality_id' => 2],
            ['discipline_id' => 18, 'speciality_id' => 2],

            ['discipline_id' => 1,  'speciality_id' => 3],
            ['discipline_id' => 2,  'speciality_id' => 3],
            ['discipline_id' => 3,  'speciality_id' => 3],
            ['discipline_id' => 4,  'speciality_id' => 3],
            ['discipline_id' => 5,  'speciality_id' => 3],
            ['discipline_id' => 7,  'speciality_id' => 3],
            ['discipline_id' => 8,  'speciality_id' => 3],
            ['discipline_id' => 9,  'speciality_id' => 3],
            ['discipline_id' => 10, 'speciality_id' => 3],
            ['discipline_id' => 11, 'speciality_id' => 3],
            ['discipline_id' => 12, 'speciality_id' => 3],
            ['discipline_id' => 13, 'speciality_id' => 3],
            ['discipline_id' => 14, 'speciality_id' => 3],
            ['discipline_id' => 15, 'speciality_id' => 3],
            ['discipline_id' => 16, 'speciality_id' => 3],
            ['discipline_id' => 17, 'speciality_id' => 3],
            ['discipline_id' => 18, 'speciality_id' => 3],

            ['discipline_id' => 1,  'speciality_id' => 4],
            ['discipline_id' => 2,  'speciality_id' => 4],
            ['discipline_id' => 3,  'speciality_id' => 4],
            ['discipline_id' => 4,  'speciality_id' => 4],
            ['discipline_id' => 5,  'speciality_id' => 4],
            ['discipline_id' => 7,  'speciality_id' => 4],
            ['discipline_id' => 8,  'speciality_id' => 4],
            ['discipline_id' => 9,  'speciality_id' => 4],
            ['discipline_id' => 10, 'speciality_id' => 4],
            ['discipline_id' => 11, 'speciality_id' => 4],
            ['discipline_id' => 12, 'speciality_id' => 4],
            ['discipline_id' => 13, 'speciality_id' => 4],
            ['discipline_id' => 14, 'speciality_id' => 4],
            ['discipline_id' => 15, 'speciality_id' => 4],
            ['discipline_id' => 16, 'speciality_id' => 4],
            ['discipline_id' => 17, 'speciality_id' => 4],
            ['discipline_id' => 18, 'speciality_id' => 4],

            ['discipline_id' => 1,  'speciality_id' => 5],
            ['discipline_id' => 2,  'speciality_id' => 5],
            ['discipline_id' => 3,  'speciality_id' => 5],
            ['discipline_id' => 4,  'speciality_id' => 5],
            ['discipline_id' => 5,  'speciality_id' => 5],
            ['discipline_id' => 7,  'speciality_id' => 5],
            ['discipline_id' => 8,  'speciality_id' => 5],
            ['discipline_id' => 9,  'speciality_id' => 5],

            ['discipline_id' => 1, 'speciality_id' => 6],
            ['discipline_id' => 2,  'speciality_id' => 6],
            ['discipline_id' => 3,  'speciality_id' => 6],
            ['discipline_id' => 4,  'speciality_id' => 6],
            ['discipline_id' => 5,  'speciality_id' => 6],
            ['discipline_id' => 7,  'speciality_id' => 6],
            ['discipline_id' => 8,  'speciality_id' => 6],
            ['discipline_id' => 9,  'speciality_id' => 6],

            ['discipline_id' => 1,  'speciality_id' => 7],
            ['discipline_id' => 2,  'speciality_id' => 7],
            ['discipline_id' => 3,  'speciality_id' => 7],
            ['discipline_id' => 4,  'speciality_id' => 7],
            ['discipline_id' => 5,  'speciality_id' => 7],
            ['discipline_id' => 7,  'speciality_id' => 7],
            ['discipline_id' => 8,  'speciality_id' => 7],
            ['discipline_id' => 9,  'speciality_id' => 7],

            ['discipline_id' => 1, 'speciality_id' => 8],
            ['discipline_id' => 2,  'speciality_id' => 8],
            ['discipline_id' => 3,  'speciality_id' => 8],
            ['discipline_id' => 4,  'speciality_id' => 8],
            ['discipline_id' => 5,  'speciality_id' => 8],
            ['discipline_id' => 7,  'speciality_id' => 8],
            ['discipline_id' => 8,  'speciality_id' => 8],
            ['discipline_id' => 9,  'speciality_id' => 8],

            ['discipline_id' => 1,  'speciality_id' => 9],
            ['discipline_id' => 2,  'speciality_id' => 9],
            ['discipline_id' => 3,  'speciality_id' => 9],
            ['discipline_id' => 4,  'speciality_id' => 9],
            ['discipline_id' => 5,  'speciality_id' => 9],
            ['discipline_id' => 7,  'speciality_id' => 9],
            ['discipline_id' => 8,  'speciality_id' => 9],
            ['discipline_id' => 9,  'speciality_id' => 9],

            ['discipline_id' => 1,  'speciality_id' => 10],
            ['discipline_id' => 2,  'speciality_id' => 10],
            ['discipline_id' => 3,  'speciality_id' => 10],
            ['discipline_id' => 4,  'speciality_id' => 10],
            ['discipline_id' => 5,  'speciality_id' => 10],
            ['discipline_id' => 7,  'speciality_id' => 10],
            ['discipline_id' => 8,  'speciality_id' => 10],
            ['discipline_id' => 9,  'speciality_id' => 10],

            ['discipline_id' => 1,  'speciality_id' => 11],
            ['discipline_id' => 2,  'speciality_id' => 11],
            ['discipline_id' => 3,  'speciality_id' => 11],
            ['discipline_id' => 4,  'speciality_id' => 11],
            ['discipline_id' => 5,  'speciality_id' => 11],
            ['discipline_id' => 7,  'speciality_id' => 11],
            ['discipline_id' => 8,  'speciality_id' => 11],
            ['discipline_id' => 9,  'speciality_id' => 11],

            ['discipline_id' => 1,  'speciality_id' => 12],
            ['discipline_id' => 2,  'speciality_id' => 12],
            ['discipline_id' => 3,  'speciality_id' => 12],
            ['discipline_id' => 4,  'speciality_id' => 12],
            ['discipline_id' => 5,  'speciality_id' => 12],
            ['discipline_id' => 7,  'speciality_id' => 12],
            ['discipline_id' => 8,  'speciality_id' => 12],
            ['discipline_id' => 9,  'speciality_id' => 12],

            ['discipline_id' => 1,  'speciality_id' => 13],
            ['discipline_id' => 2,  'speciality_id' => 13],
            ['discipline_id' => 3,  'speciality_id' => 13],
            ['discipline_id' => 4,  'speciality_id' => 13],
            ['discipline_id' => 5,  'speciality_id' => 13],
            ['discipline_id' => 7,  'speciality_id' => 13],
            ['discipline_id' => 8,  'speciality_id' => 13],
            ['discipline_id' => 9,  'speciality_id' => 13],

            ['discipline_id' => 1,  'speciality_id' => 14],
            ['discipline_id' => 2,  'speciality_id' => 14],
            ['discipline_id' => 3,  'speciality_id' => 14],
            ['discipline_id' => 4,  'speciality_id' => 14],
            ['discipline_id' => 5,  'speciality_id' => 14],
            ['discipline_id' => 7,  'speciality_id' => 14],
            ['discipline_id' => 8,  'speciality_id' => 14],
            ['discipline_id' => 9,  'speciality_id' => 14],

            ['discipline_id' => 1,  'speciality_id' => 15],
            ['discipline_id' => 2,  'speciality_id' => 15],
            ['discipline_id' => 3,  'speciality_id' => 15],
            ['discipline_id' => 4,  'speciality_id' => 15],
            ['discipline_id' => 5,  'speciality_id' => 15],
            ['discipline_id' => 7,  'speciality_id' => 15],
            ['discipline_id' => 8,  'speciality_id' => 15],
            ['discipline_id' => 9,  'speciality_id' => 15],

            ['discipline_id' => 1,  'speciality_id' => 16],
            ['discipline_id' => 2,  'speciality_id' => 16],
            ['discipline_id' => 3,  'speciality_id' => 16],
            ['discipline_id' => 4,  'speciality_id' => 16],
            ['discipline_id' => 5,  'speciality_id' => 16],
            ['discipline_id' => 7,  'speciality_id' => 16],
            ['discipline_id' => 8,  'speciality_id' => 16],
            ['discipline_id' => 9,  'speciality_id' => 16],

            ['discipline_id' => 1,  'speciality_id' => 17],
            ['discipline_id' => 2,  'speciality_id' => 17],
            ['discipline_id' => 3,  'speciality_id' => 17],
            ['discipline_id' => 4,  'speciality_id' => 17],
            ['discipline_id' => 5,  'speciality_id' => 17],
            ['discipline_id' => 7,  'speciality_id' => 17],
            ['discipline_id' => 8,  'speciality_id' => 17],
            ['discipline_id' => 9,  'speciality_id' => 17],

            ['discipline_id' => 1,  'speciality_id' => 18],
            ['discipline_id' => 2,  'speciality_id' => 18],
            ['discipline_id' => 3,  'speciality_id' => 18],
            ['discipline_id' => 4,  'speciality_id' => 18],
            ['discipline_id' => 5,  'speciality_id' => 18],
            ['discipline_id' => 7,  'speciality_id' => 18],
            ['discipline_id' => 8,  'speciality_id' => 18],
            ['discipline_id' => 9,  'speciality_id' => 18],

            ['discipline_id' => 1,  'speciality_id' => 19],
            ['discipline_id' => 2,  'speciality_id' => 19],
            ['discipline_id' => 3,  'speciality_id' => 19],
            ['discipline_id' => 4,  'speciality_id' => 19],
            ['discipline_id' => 5,  'speciality_id' => 19],
            ['discipline_id' => 7,  'speciality_id' => 19],
            ['discipline_id' => 8,  'speciality_id' => 19],
            ['discipline_id' => 9,  'speciality_id' => 19],

            ['discipline_id' => 1,  'speciality_id' => 20],
            ['discipline_id' => 2,  'speciality_id' => 20],
            ['discipline_id' => 3,  'speciality_id' => 20],
            ['discipline_id' => 4,  'speciality_id' => 20],
            ['discipline_id' => 5,  'speciality_id' => 20],
            ['discipline_id' => 7,  'speciality_id' => 20],
            ['discipline_id' => 8,  'speciality_id' => 20],
            ['discipline_id' => 9,  'speciality_id' => 20],

            ['discipline_id' => 1,  'speciality_id' => 21],
            ['discipline_id' => 2,  'speciality_id' => 21],
            ['discipline_id' => 3,  'speciality_id' => 21],
            ['discipline_id' => 4,  'speciality_id' => 21],
            ['discipline_id' => 5,  'speciality_id' => 21],
            ['discipline_id' => 7,  'speciality_id' => 21],
            ['discipline_id' => 8,  'speciality_id' => 21],
            ['discipline_id' => 9,  'speciality_id' => 21],

            ['discipline_id' => 1,  'speciality_id' => 22],
            ['discipline_id' => 2,  'speciality_id' => 22],
            ['discipline_id' => 3,  'speciality_id' => 22],
            ['discipline_id' => 4,  'speciality_id' => 22],
            ['discipline_id' => 5,  'speciality_id' => 22],
            ['discipline_id' => 7,  'speciality_id' => 22],
            ['discipline_id' => 8,  'speciality_id' => 22],
            ['discipline_id' => 9,  'speciality_id' => 22],

            ['discipline_id' => 1,  'speciality_id' => 23],
            ['discipline_id' => 2,  'speciality_id' => 23],
            ['discipline_id' => 3,  'speciality_id' => 23],
            ['discipline_id' => 4,  'speciality_id' => 23],
            ['discipline_id' => 5,  'speciality_id' => 23],
            ['discipline_id' => 7,  'speciality_id' => 23],
            ['discipline_id' => 8,  'speciality_id' => 23],
            ['discipline_id' => 9,  'speciality_id' => 23],

            ['discipline_id' => 1,  'speciality_id' => 24],
            ['discipline_id' => 2,  'speciality_id' => 24],
            ['discipline_id' => 3,  'speciality_id' => 24],
            ['discipline_id' => 4,  'speciality_id' => 24],
            ['discipline_id' => 5,  'speciality_id' => 24],
            ['discipline_id' => 7,  'speciality_id' => 24],
            ['discipline_id' => 8,  'speciality_id' => 24],
            ['discipline_id' => 9,  'speciality_id' => 24],

            ['discipline_id' => 1,  'speciality_id' => 25],
            ['discipline_id' => 2,  'speciality_id' => 25],
            ['discipline_id' => 3,  'speciality_id' => 25],
            ['discipline_id' => 4,  'speciality_id' => 25],
            ['discipline_id' => 5,  'speciality_id' => 25],
            ['discipline_id' => 7,  'speciality_id' => 25],
            ['discipline_id' => 8,  'speciality_id' => 25],
            ['discipline_id' => 9,  'speciality_id' => 25],

            ['discipline_id' => 1,  'speciality_id' => 26],
            ['discipline_id' => 2,  'speciality_id' => 26],
            ['discipline_id' => 3,  'speciality_id' => 26],
            ['discipline_id' => 4,  'speciality_id' => 26],
            ['discipline_id' => 5,  'speciality_id' => 26],
            ['discipline_id' => 7,  'speciality_id' => 26],
            ['discipline_id' => 8,  'speciality_id' => 26],
            ['discipline_id' => 9,  'speciality_id' => 26],

            ['discipline_id' => 1,  'speciality_id' => 27],
            ['discipline_id' => 2,  'speciality_id' => 27],
            ['discipline_id' => 3,  'speciality_id' => 27],
            ['discipline_id' => 4,  'speciality_id' => 27],
            ['discipline_id' => 5,  'speciality_id' => 27],
            ['discipline_id' => 7,  'speciality_id' => 27],
            ['discipline_id' => 8,  'speciality_id' => 27],
            ['discipline_id' => 9,  'speciality_id' => 27],

            ['discipline_id' => 1,  'speciality_id' => 28],
            ['discipline_id' => 2,  'speciality_id' => 28],
            ['discipline_id' => 3,  'speciality_id' => 28],
            ['discipline_id' => 4,  'speciality_id' => 28],
            ['discipline_id' => 5,  'speciality_id' => 28],
            ['discipline_id' => 7,  'speciality_id' => 28],
            ['discipline_id' => 8,  'speciality_id' => 28],
            ['discipline_id' => 9,  'speciality_id' => 28],

            ['discipline_id' => 1,  'speciality_id' => 29],
            ['discipline_id' => 2,  'speciality_id' => 29],
            ['discipline_id' => 3,  'speciality_id' => 29],
            ['discipline_id' => 4,  'speciality_id' => 29],
            ['discipline_id' => 5,  'speciality_id' => 29],
            ['discipline_id' => 7,  'speciality_id' => 29],
            ['discipline_id' => 8,  'speciality_id' => 29],
            ['discipline_id' => 9,  'speciality_id' => 29],

            ['discipline_id' => 1,  'speciality_id' => 30],
            ['discipline_id' => 2,  'speciality_id' => 30],
            ['discipline_id' => 3,  'speciality_id' => 30],
            ['discipline_id' => 4,  'speciality_id' => 30],
            ['discipline_id' => 5,  'speciality_id' => 30],
            ['discipline_id' => 7,  'speciality_id' => 30],
            ['discipline_id' => 8,  'speciality_id' => 30],
            ['discipline_id' => 9,  'speciality_id' => 30],
        ]);
    }
}
